server {
  listen 80;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html;

  location = /admin { try_files /index.html =404; }
  location = /dashboard { try_files /index.html =404; }
  location = /login { try_files /index.html =404; }
  location = /signup { try_files /index.html =404; }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /auth/ {
    proxy_pass http://auth-service:3001/auth/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass_request_headers on;
    proxy_cookie_path / /;
  }

  location /shorten {
    proxy_pass http://url-service:3002/shorten;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Authorization $http_authorization;
  }

  location /urls {
    proxy_pass http://url-service:3002/urls;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Authorization $http_authorization;
  }

  location ~ "^/([A-Za-z0-9]{4,10})$" {
    proxy_pass http://url-service:3002/$1;
    proxy_set_header Host $host;
  }

  location /s/ {
    proxy_pass http://url-service:3002/s/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /analytics/ {
    proxy_pass http://analytics-service:3003/analytics/;
    proxy_set_header Host $host;
  }

  location /admin/ {
    proxy_pass http://cleanup-worker:3004/admin/;
    proxy_set_header Host $host;
  }
}
