apiVersion: v1
kind: Secret
metadata:
  name: linkshrink-secret
type: Opaque
stringData:
  JWT_SECRET: "bTMeK1+H3Fh2juFA+4i6h5zgUHwij3s0cWV72XgKpwBj6WTYFDKr93nb2hjPDpdz"
  POSTGRES_PASSWORD: "postgres"
  RABBITMQ_PASSWORD: "guest"
