apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-secret.yaml
  - 02-configmap.yaml
  - 03-postgres-init-configmap.yaml
  - 04-postgres.yaml
  - 05-redis.yaml
  - 06-rabbitmq.yaml
  - 07-auth-service.yaml
  - 08-url-service.yaml
  - 09-analytics-service.yaml
  - 10-cleanup-worker.yaml
  - 11-frontend.yaml
  - 12-ingress.yaml
