apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-secret-provider.yaml
  - 02-configmap.yaml
  - 03-service-accounts.yaml
  - 04-rds-init-job.yaml
  - 05-auth-service.yaml
  - 06-url-service.yaml
  - 07-analytics-service.yaml
  - 08-cleanup-worker.yaml
  - 09-frontend.yaml
  - 10-ingress.yaml
  - 11-external-services.yaml
